import os
import threading
import time
from dotenv import load_dotenv
import streamlit as st

# Load .env for local development
load_dotenv()

# Inject Streamlit Cloud secrets as environment variables
for key, value in st.secrets.items():
    os.environ[str(key)] = str(value)

import requests
import datetime
import uvicorn
from main import app as fastapi_app

@st.cache_resource
def start_fastapi_server():
    """Start FastAPI in a background daemon thread. Runs once across all sessions."""
    def run():
        uvicorn.run(fastapi_app, host="127.0.0.1", port=8000, log_level="error")
    thread = threading.Thread(target=run, daemon=True)
    thread.start()
    time.sleep(1)  # Give the server a moment to be ready

start_fastapi_server()

BASE_URL = "http://127.0.0.1:8000"

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        with st.spinner("Planning your trip..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# 🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
            # **Created by:** Atriyo's Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(markdown_content)
        else:
            st.error(" Bot failed to respond: " + response.text)

    except Exception as e:
        raise f"The response failed due to {e}"